// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "mschart2.h"

/////////////////////////////////////////////////////////////////////////////
// CMschart2

IMPLEMENT_DYNCREATE(CMschart2, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMschart2 properties

/////////////////////////////////////////////////////////////////////////////
// CMschart2 operations
